### ISSUE TITLE
The _core:default_config_hash is removed from existing config when installing OE Bootstrap Theme Paragraphs

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#140]
This happens when the existing config is updated during install from the following overrides in `modules/oe_bootstrap_theme_paragraphs/config/overrides`:

```
core.entity_form_display.paragraph.oe_links_block.default.yml
core.entity_form_display.paragraph.oe_social_media_follow.default.yml
core.entity_view_display.paragraph.oe_links_block.default.yml
core.entity_view_display.paragraph.oe_social_media_follow.default.yml
```

The 5th config override in this directory contains a  _core:default_config_hash:
```
field.field.paragraph.oe_social_media_follow.field_oe_social_media_variant.yml
```

OE Bootstrap Theme version: 1.0.0-alpha4

**Comment by abel-santos-corral** [comment]
This will be solved on Jira ticket [OEL-847](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-847)

**Comment by brummbar** [comment]
Should be fixed.
