### ISSUE TITLE
PHP Notice when Listing item block title is not set

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#141]
I'm getting the following PHP notice when the (not required) title field of oe_list_item_block par. type is not set:

```
Notice: Trying to get property 'value' of non-object in oe_bootstrap_theme_preprocess_paragraph__oe_list_item_block() (line 132 of themes/contrib/oe_bootstrap_theme/includes/paragraphs.inc).
```
Please note that this is on OE Bootstrap Theme 1.0.0-alpha3, on 1.0.0-alpha4 this code was moved to: https://github.com/openeuropa/oe_bootstrap_theme/blob/1.0.0-alpha4/modules/oe_bootstrap_theme_paragraphs/oe_bootstrap_theme_paragraphs.module#L156

**Comment by AaronGilMartinez** [comment]
Closing, paragraphs modules including processing were migrated to https://github.com/openeuropa/oe_whitelabel. Paragraphs get the title value directly rather from ListInterface::first() method solved in https://github.com/openeuropa/oe_whitelabel/pull/105.
