### ISSUE TITLE
JS error on pages using select template override

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#145]
The `/templates/overrides/form/select.html.twig` template always attaches the slimselect library, see [code](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/overrides/form/select.html.twig#L13).

This causes js errors on pages where the template is used, but there is no element with `.multi-select` class:

`Uncaught Error: Could not find select element`

We fixed this issue by overriding this template and only attaching the library when `element['#multiple']` is true.

**Comment by brummbar** [comment]
Is the issue fixed @kp77 ?

**Comment by kp77** [comment]
Hi @brummbar,

No, the issue is not fixed yet. I see a PR that makes the slim select library optional #224, but this still doesn't deal with the issue, that if there is no element on the page with `.multi-select` class, the library's script throws the error described above.

As you can see [here](https://github.com/digit-devs/echo-ucpkn-dev/pull/164/files#diff-8c51326320a846b04425f47305d30f8c63c67bf98b9b1a76e75001abdec4af29R18-R24), we fixed this in our override by only including the library together with setting the class.

**Comment by brummbar** [comment]
We removed completely slim_select on #239 .
