### ISSUE TITLE
Grid row is displaying empty cards

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#161]
### Description
Grid row is not being displayed correctly, the cards are empty.

### Steps to reproduce
Go to `patterns/grid_row` and see the empty cards.

I've tested replacing `{{- title.content -}}` with `{{- title -}}` in `assets/bcl/bcl-card/bcl-card.html.twig`, that makes the title visible.

**Comment by tibi2303** [comment]
seems that the grid layout for cards works accordingly inside the /patterns page, i will close it. please feel free to reopen if it's still the case.
