### ISSUE TITLE
Patterns with missing svg icons

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#165]
### Description

In `/patterns` page, there are errors in browser's console, saying these files are not found:

/assets/icons/bootstrap-icons.svg
/icons.svg

In [web/themes/contrib/oe_bootstrap_theme/oe_bootstrap_theme.theme](oe_bootstrap_theme_preprocess) this path is being fixed only for `bcl_icon_path`. But there are also `icons_path` and `path` fields in the patterns using icons. For these there is no preprocessing. This seems to be the reason why the errors happen.

**Comment by tibi2303** [comment]
seems that the svg sprite works in /patterns page. I will close this.
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/36895476/220945132-3ca43401-7d91-4dca-9c58-6bc2b28dad59.png">
