### ISSUE TITLE
Error in slimselect library inclusion

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#166]
### Description

In /styleguide there are javascript errors because of the attached library `oe_bootstrap_theme/slimselect`.
In `templates/overrides/form/select.html.twig`, this library should only be included if the element is multiple.

**Comment by kp77** [comment]
Hi @dxvargas,

I think this is the same issue I described here #145 Could you confirm?

**Comment by dxvargas** [comment]
Yes @kp77 it is the same. I did look for it but I didn't find it.
Anyway, I close this issue. Thanks.
