### ISSUE TITLE
Refactor Dropdown pattern with BCL component

### ISSUE THREAD

**Issue by papegaill** [openeuropa/oe_bootstrap_theme#20]

**Comment by abel-santos-corral** [comment]
Handled at: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-412

**Comment by cmarcmar** [comment]
The problem is that in the patterns.inc it tries to access $variables['items'] instead of the new name $variables['dropdown_items'].

Furthermore, an isset check was missing when trying to access and manipulate the variable $item['#url'] causing an error.
