### ISSUE TITLE
Conversion in featured media pattern preprocess breaks pattern preview

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#208]
There's a [conversion](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.0.0-alpha7/includes/pattern.inc#L141-L148) added to `oe_bootstrap_theme_preprocess_pattern_featured_media` that causes the following error on the /patterns page (1.0.0-alpha7 version):

```
TypeError: Argument 1 passed to Drupal\oe_bootstrap_theme\ValueObject\ImageValueObject::__construct() must be of the type string, null given, called in themes/contrib/oe_bootstrap_theme/src/ValueObject/ImageValueObject.php on line 72 in Drupal\oe_bootstrap_theme\ValueObject\ImageValueObject->__construct() (line 55 of themes/contrib/oe_bootstrap_theme/src/ValueObject/ImageValueObject.php).
```
The code is to be removed in the future according to the comments.

**Comment by tibi2303** [comment]
The patterns page works now so this was fixed.
