### ISSUE TITLE
Missing styling for multiple value fields

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#217]
Multiple value form fields are not looking good. They use a heading H4 for the label:
`<h4 class="label">Label</h4>`
The class "label" is not doing much there. It's just a H4 that looks too large in comparison with all other labels.

Also the "Show row weights" link and drag icons look not styled

**Comment by brummbar** [comment]
Not sure which forms you are referring too, we don't offer styling for everything possible. If we are not offering styling for something we don't use, feel free to contribute it.
