### ISSUE TITLE
Change class for secondary buttons

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#218]
In [BCL mockups](https://oelibrary.netlify.app/default/?path=/story/features-users--edit) secondary buttons have class "btn-light" (see the image button).
In OE Bootstrap Theme [repo](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.0.0-alpha7/templates/overrides/form/input--submit.html.twig) they have "btn-secondary".

The result looks quite different. Please change the class in one place or the other, to be the same in both places.

**Comment by tibi2303** [comment]
The BCL secondary buttons also uses btn-secondary, check the link you provided - maybe it was the case when this issue was opened but not anymore. I will close this.
