### ISSUE TITLE
OEL-1380: Paragraph field bare template suggestion should not depend on oe_bootstrap_theme_paragraphs

### ISSUE THREAD

**Issue by claudiu-cristea** [openeuropa/oe_bootstrap_theme#221]
## Problem

In 9a44fe1d6b4a410667406f1a41ec98e155bbde43, the `field__bare` suggestion was moved from the theme to `oe_bootstrap_theme_paragraphs` sub-module. The `oe_bootstrap_theme_paragraphs` sub-module is designed to bridge between `oe_bootstrap_theme` and `oe_paragraphs` module. But this is not the case for all projects. Some projects, such as Joinup, are using the `paragraphs` module without depending on `oe_paragraphs`. The change from 9a44fe1d6b4a410667406f1a41ec98e155bbde43 did introduce a regression when we updated OE Bootstrap Theme from an early version to `1.0.0-alpha7`.

## Proposal

Move back (revert) the suggestion alter to `includes/field.inc` so that all projects can benefit for this template suggestion, even they are not using `oe_paragraphs`.

**Comment by brummbar** [comment]
We decided to not offer this in oe_bootstrap_theme anymore.
