### ISSUE TITLE
Inconsistent form element widths in forms

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#240]
The [fieldset template](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.0.0-alpha8/templates/overrides/form/fieldset.html.twig#L45) applies a 'col-sm-10' class on the fieldset wrapper element. Because of this, the widths of form elements inside a fieldset are smaller than elements outside of a fieldset.

Because of this class, the look of the facets form filters for search pages is different from the [BCL example](https://oelibrary.netlify.app/default/?path=/story/features-search--default).

![Screenshot 2022-05-17 at 11 05 31](https://user-images.githubusercontent.com/648045/168774218-fef8701b-d864-41c8-83d5-833804f84210.png)

**Comment by brummbar** [comment]
Will be fixed in #360 .

**Comment by brummbar** [comment]
Closing as fixed.
