### ISSUE TITLE
Return type of getIterator() at ValueObjectBase.php

### ISSUE THREAD

**Issue by abel-santos-corral** [openeuropa/oe_bootstrap_theme#246]
At ERA project we have installed php 8.1 and when running tests we get the following message:

`Deprecated: Return type of Drupal\oe_bootstrap_theme\ValueObject\ValueObjectBase::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/abel-santos-corral/openeuropa/era-era-dev/web/themes/contrib/oe_bootstrap_theme/src/ValueObject/ValueObjectBase.php on line 29
`

Which happens at this function:
`  /**
   * {@inheritdoc}
   */
  public function getIterator() {
    return new \ArrayIterator($this->getArray());
  }`

Which is at ValueObjectBase.php. Could you please check if there's compatibility problem at php 8.1 at that class?

**Comment by Aporie** [comment]
Patch attached:
[oe_bootstrap_theme_php81_compat.txt](https://github.com/openeuropa/oe_bootstrap_theme/files/9121612/oe_bootstrap_theme_php81_compat.txt)

**Comment by brummbar** [comment]
We don't support 8.1 yet.
