### ISSUE TITLE
Table theming has been removed

### ISSUE THREAD

**Issue by bogdan24pop** [openeuropa/oe_bootstrap_theme#249]
The styles for the table has been removed from the base theme. 
See: https://github.com/openeuropa/oe_bootstrap_theme/pull/177
Why the table theming has been removed?

**Comment by brummbar** [comment]
We removed it because it was not correctly supported at the moment, if I remember correctly.

**Comment by brummbar** [comment]
We are adding it back via #290 .

**Comment by brummbar** [comment]
Fixed in #290 .
