### ISSUE TITLE
Missing comma in field--comment.html.twig template

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#251]
After enabling comment module, I received the following error when trying to use the comment field:

```
Twig\Error\SyntaxError: A hash value must be followed by a comma. Unexpected token "string" of value "border_variant" ("punctuation" expected with value ","). in Twig\TokenStream->expect() (line 19 of themes/contrib/oe_bootstrap_theme/templates/overrides/field/field--comment.html.twig).
```

Seems like a comma is missing from the end of [this line](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.0.0-beta2/templates/overrides/field/field--comment.html.twig#L18).

**Comment by brummbar** [comment]
Fixed.
