### ISSUE TITLE
Put back title tag in pattern listing

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/oe_bootstrap_theme#252]
Title tag parameter "title_tag" was removed.
https://github.com/openeuropa/oe_bootstrap_theme/pull/191/files#diff-31df009187d50656aa871ce3bdfd34fa4e789df3b93de1813e3fc970a1dfbbd6L12

Was this intended? Anyway, it doesn't seem a change in the right direction.
Pattern '@oe-bcl/listing' supports this parameter, why remove it here?

**Comment by brummbar** [comment]
Our patterns aren't meant to support all the options that those templates have. We try to uniform how our patterns render, so we dropped most of the tag customisation. The original template can be used directly if needed.
