### ISSUE TITLE
Media Library pagination not working

### ISSUE THREAD

**Issue by bogdan24pop** [openeuropa/oe_bootstrap_theme#257]
The media library pagination is not working properly, if you click on next page an Ajax error occurs.  Seems that the `js-pager__items` class is missing.

**Comment by brummbar** [comment]
Hello @bogdan24pop , of which media library are we talking about?

**Comment by brummbar** [comment]
Unfortunately in the current implementation, classes are lost when rendering the pager.

**Comment by msnassar** [comment]
@brummbar  Without "js-pager__items" being added to the pagination list, the ajax pagination is not working. 
Steps to reproduce:
- Enable ajax in any view that is displayed using the oe_bootstrap_theme.
- When clicking on a pagination item, the page is being reloaded.

All core themes set this class in pager.html.twig and views-mini-pager.html.twig

I created a ticket for BCL too https://github.com/openeuropa/bootstrap-component-library/issues/565

If you agree with the [proposed solution](https://github.com/openeuropa/bootstrap-component-library/pull/566), we then need to add the following to the pagination pattern:
`'list_attributes': create_attribute({class: ['js-pager__items']}),`

**Comment by AaronGilMartinez** [comment]
Fixed in #420
