### ISSUE TITLE
Error when using oe_bootstrap_theme

### ISSUE THREAD

**Issue by pschelte-extec** [openeuropa/oe_bootstrap_theme#271]
Hello,
Following the installation and the activation as mentioned in the documentation, when I set this theme as default I have this error when displaying the site :

<pre>
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "navbar" plugin does not exist. Valid plugin IDs for Drupal\ui_patterns\UiPatternsManager are: in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

Drupal\Core\Plugin\DefaultPluginManager->getDefinition() (Line: 42)
Drupal\ui_patterns\UiPatterns::getPatternDefinition() (Line: 46)
Drupal\ui_patterns\Element\Pattern::processRenderArray()
call_user_func_array() (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback() (Line: 772)
Drupal\Core\Render\Renderer->doCallback() (Line: 363)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 47)
__TwigTemplate_226cc050034d8133026eb4a6d06d49d46ede455160c45546ccfd53912c44ed7e->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 80)
__TwigTemplate_35ad3dd75c6a67737cf65bfa272890ea45f7c6e88d71e88a19dbb65794d5089f->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 162)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 163)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
call_user_func() (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() (Line: 164)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 58)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 23)
Stack\StackedHttpKernel->handle() (Line: 709)
Drupal\Core\DrupalKernel->handle() (Line: 19)
</pre>

It looks that I miss a dependency somewhere: navbar ? from which module ?

Kind regards

Philippe

**Comment by brummbar** [comment]
Hello @pschelte-extec , from the log it seems that the navbar pattern is not found in your installation, but it's [present in our folders](https://github.com/openeuropa/oe_bootstrap_theme/tree/1.x/templates/patterns/navbar).
Can you give us more information on which version you are using?

**Comment by pschelte-extec** [comment]
Hello  @brummbar , 
since this report I have upgraded to oe_theme 3.0.0-beta18 with ui_patterns 1.3.0 and now I have another error :

The website encountered an unexpected error. Please try again later.

Twig\Error\LoaderError:
 Unable to find template 
"modules/contrib/ui_patterns/templates/pattern-navigation-menu.html.twig"
 (looked into: themes/contrib/oe_theme/components). in Twig\Loader\FilesystemLoader->findTemplate() (line 16 of themes/contrib/oe_theme/modules/oe_theme_helper/templates/oe-theme-helper-site-navigation.html.twig). OpenEuropa\Twig\Loader\EuropaComponentLibraryLoader->findTemplate() (Line: 169)
Twig\Loader\FilesystemLoader->exists() (Line: 87)
Twig\Loader\ChainLoader->getCacheKey() (Line: 299)
Twig\Environment->getTemplateClass() (Line: 205)
Drupal\Core\Template\TwigEnvironment->getTemplateClass() (Line: 381)
Twig\Environment->loadTemplate() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 41)
__TwigTemplate_334b35539e08011b9fb4023a08f7070d9b8168b42224356ef070412a2629d3ae->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 80)
__TwigTemplate_0a7c8f997d3be29f0e12023f935ba4234079d7036403434a8e5bf3879cbdd5ef->block_content() (Line: 182)
Twig\Template->displayBlock() (Line: 68)
__TwigTemplate_0a7c8f997d3be29f0e12023f935ba4234079d7036403434a8e5bf3879cbdd5ef->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 435)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 77)
__TwigTemplate_cfd12f07c069a3f4bf3a51b02c338248045c6647bc91bbe9f05432ff59d2af6c->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter() (Line: 86)
__TwigTemplate_5805e017dd61590cafc27cce409df48ee1a33a2eba2454bbc59c05a95db0783b->doDisplay() (Line: 405)
Twig\Template->displayWithErrorHandling() (Line: 378)
Twig\Template->display() (Line: 390)
Twig\Template->render() (Line: 55)
twig_render_template() (Line: 384)
Drupal\Core\Theme\ThemeManager->render() (Line: 422)
Drupal\Core\Render\Renderer->doRender() (Line: 201)
Drupal\Core\Render\Renderer->render() (Line: 162)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 163)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
call_user_func() (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() (Line: 174)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 81)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 58)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 23)
Stack\StackedHttpKernel->handle() (Line: 709)
Drupal\Core\DrupalKernel->handle() (Line: 19)`
`
I can remove the error by commenting out all the code in /home/devlin/sante-flwph-reference/web/themes/contrib/oe_theme/modules/oe_theme_helper/templates/oe-theme-helper-site-navigation.html.twig and running dcweb drush cache:rebuild but it is not a solution.

**Comment by brummbar** [comment]
Uhm this is the issue queue for oe_bootstrap_theme, oe_theme is here https://github.com/openeuropa/oe_theme .
