### ISSUE TITLE
Views mini pager display [1] when the view result is empty

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_bootstrap_theme#278]
Views mini pager displays [1] when the view result is empty
https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/overrides/views/views-mini-pager.html.twig

**Comment by tibi2303** [comment]
Is it still the case? if it is, please can you provide a screenshot of this bug or more info

**Comment by msnassar** [comment]
@tibi2303 Yes it is. See here
![image](https://user-images.githubusercontent.com/15343499/223980334-6e344cf2-727d-4857-b9a2-d2d50e4a8528.png)

It seems it displays [1] all the time. The following view is displaying 25 record per page. We have 3 records, but [1] is displayed!
![image](https://user-images.githubusercontent.com/15343499/223981030-3fdc8e3e-fd42-4487-add2-76ba4f786b75.png)

You could try to reproduce using a view, make sure to use mini pager
