### ISSUE TITLE
Error into menu inc file after log in

### ISSUE THREAD

**Issue by paulanavarroDAW** [openeuropa/oe_bootstrap_theme#280]
Hi,

We found an error using this module on our project.
When you are logged in via ecas, with a user that is not an administrator,
we get this error when we try to access some pages:

So in Drupal logs, we found the following error:
Error: Call to a member function access() on null in oe_bootstrap_theme_prepare_menu_local_task_links() (line 162)

We detected this error on the user profile and node pages.
To reproduce this issue:
- User with a different rol than administrator
- We log in via ecas
- Try to access to the user profile or some node.

PR: https://github.com/openeuropa/oe_bootstrap_theme/pull/279

**Comment by brummbar** [comment]
Hello @paulanavarroDAW , did you try a more recent version of the theme? We reworked that method recently.

**Comment by brummbar** [comment]
The error seems to be the same reported here #285 and fixed in #286.
