### ISSUE TITLE
Inpage navigation ScrollSpy offset

### ISSUE THREAD

**Issue by peterserfozo** [openeuropa/oe_bootstrap_theme#284]
A correct offset value should be set in https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/resources/js/inpage_navigation.js#L23 like this:
```
      Array.prototype.forEach.call(document.querySelectorAll('nav.bcl-inpage-navigation'), function (nav) {
        instances.push(new bootstrap.ScrollSpy(document.body, {
          target: nav,
          offset: 60,
        }));
      });
```

Because of the section margin bottoms (`mb-5`) and the incorrect default offset (10), not the correct inpage navigation menu item is the active (highlighted) when a page is visited with an anchor in the URL.

Steps to reproduce:
- Visit https://civil-protection-knowledge-network.europa.eu/projects/afan#inpage-section-partner-organisations
- "Description" is the active menu item instead of "Partner organisations"

**Comment by brummbar** [comment]
@peterserfozo I opened the link and this is the result:
![image](https://user-images.githubusercontent.com/8488617/208114355-81117c96-80cb-4438-9933-e4b8dc27e1ad.png)
The offset might be caused by the toolbar, if you are logged in?

**Comment by peterserfozo** [comment]
Hi @brummbar! It works because our custom fix has been already deployed

```
(function ($, Drupal) {
  Drupal.behaviors.ucpknInpageNavigationSections = {
    attach: function (context, settings) {
      const $scroll_spy = bootstrap.ScrollSpy.getInstance($('body'));
      if ($scroll_spy) {
        // The default offset value is 10. We need a higher value, because of
        // the bottom margin of the sections.
        $scroll_spy._config.offset = 60;
      }
    }
  }
} (jQuery, Drupal));
```

**Comment by brummbar** [comment]
I understand. Unfortunately, each website can have custom spacing so we cannot put a value that will satisfy everybody.
Since you gave an example of the code needed to make it work in a website, we can consider this solvable with little custom code for each website.
