### ISSUE TITLE
Pattern overview page broken after update to ui_patterns 1.5.0

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_bootstrap_theme#294]
After upgrading ui_patterns to 1.5.0, the /patterns page is broken and doesn't display patterns anymore.
![image](https://user-images.githubusercontent.com/1317919/214023754-5a7be7f0-01f1-49cc-8947-60119c8c3c97.png)

It seems https://www.drupal.org/i/3328272 made changes to the `patterns-overview-page.html.twig` template which oe_bootstrap_theme overrides and would therefore need to be updated.
Perhaps it would be best to simply remove this override?

**Comment by brummbar** [comment]
Will be fixed in next release.
