### ISSUE TITLE
Responsive tables missing the toggle to show/hide "low priority column"

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_bootstrap_theme#311]
Drupal responsive table has a toggle to show and hide the columns that have low priority. The toggle (button) exists in the DOM but do not appear on the page because of some missing styles. This is because, core is displaying it when a hidden th is found, see:
`var hiddenLength = this.$headers.filter('.priority-medium:hidden, .priority-low:hidden').length;`

**Steps to reproduce:**
- Use seven as admin theme.
- Go to /admin/content
- Go to mobile mode, you will see a link on the top of the table "Show all columns".
- Now change the admin them to oe_bootstrap_theme and do the other steps, you won't see the link!

**Suggested  fix:**
```
th.priority-low,
th.priority-medium,
td.priority-low,
td.priority-medium {
  display: none;
}

@media screen and (min-width: 38em) {
  th.priority-medium,
  td.priority-medium {
    display: table-cell;
  }
}

@media screen and (min-width: 60em) {
  th.priority-low,
  td.priority-low {
    display: table-cell;
  }
}

```

![image](https://user-images.githubusercontent.com/15343499/223986435-7c305bec-429b-4108-82ba-ed469c2a143a.png)
![image](https://user-images.githubusercontent.com/15343499/223986515-53030dfa-73f6-429c-8e1b-a0218ac255b3.png)

**Comment by tibi2303** [comment]
<img width="928" alt="image" src="https://github.com/openeuropa/oe_bootstrap_theme/assets/36895476/ca488885-2eb5-4aab-8247-e2df7f564ab2">

I see the link is displayed in oe_bootstrap_theme and maybe it was already fixed in some previous versions. From my point of view we can close this issue.

**Comment by msnassar** [comment]
Closing it as it has been fixed in https://github.com/openeuropa/oe_bootstrap_theme/pull/387
