### ISSUE TITLE
Card pattern: Do not display empty meta.

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_bootstrap_theme#316]
The card pattern is displaying empty span when a _meta_item is empty. See
https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/patterns/card/pattern-card.html.twig#L13
Would be nice to do check the emptiness of the _meta_item. e.g.
```
          {% if _meta_item is not empty %}
            <span class="text-muted me-3">{{ _meta_item }}</span>
          {% endif %}
```

**Comment by kp77** [comment]
Same in the card search variant template.
