### ISSUE TITLE
AV Portal Video is not sized correctly in featured media pattern

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_bootstrap_theme#358]
The AV Portal Video media output contains the default field wrapper. This prevents the `.ratio .ratio-16x9` classes to apply the correct sizing styles to the video iframe.

![Screenshot 2023-10-26 at 09 58 58](https://github.com/openeuropa/oe_bootstrap_theme/assets/648045/08fae4d7-7eb1-421b-b61a-09efff12d5a2)

I'm reporting it here, because OE Bootstrap Theme ships those field template overrides that remove the field wrapper from media types (for example: [remote video](https://github.com/openeuropa/oe_bootstrap_theme/blob/1.7.0/templates/overrides/field/field--media--remote-video.html.twig)).

Proposed solution: a similar override should be added extending `field--bare.html.twig` as
`templates/overrides/field/field--media--av-portal-video.html.twig`

OE Bootsrap Theme version: 1.7.0
OE Whitelabel version: 1.3.0

**Comment by brummbar** [comment]
This does not belong here though, oe_bootstrap_theme doesn't integrate with components. There are some for legacy reason, but they are wrong. They should be in oe_whitelabel.
