### ISSUE TITLE
Change description text of background for badge pattern 

### ISSUE THREAD

**Issue by peterserfozo** [openeuropa/oe_bootstrap_theme#359]
The affected line: https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/patterns/badge/badge.ui_patterns.yml#L8

Please change
`Set the background color of the badge:`
to
`Set the background color of the badge.`

We want to reuse this text on the UI and colons should not be added to description texts by convention.

**Comment by brummbar** [comment]
Fixed in #366 .
