### ISSUE TITLE
Rounded bottom border

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_bootstrap_theme#388]
The card pattern (search variant) adds bottom border to the card (https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/patterns/card/pattern-card--variant-search.html.twig#L67)
Due to the facet that bootstrap library (https://getbootstrap.com/docs/5.3/components/card) applies border radius on the `card`, we have rounded corner when the card has bottom border too!
See here https://digit-oesa.prd.fpfis.tech.ec.europa.eu/en/search
![image](https://github.com/openeuropa/oe_bootstrap_theme/assets/15343499/59b6de67-1777-4da9-9f77-3b0a88ef380d)

Have been solved in UCPKN by:
```
.card {
  // Cards with .border-bottom should not have rounded corners. 
  &.border-bottom {
    @extend .rounded-0;
  }
}
```

**Comment by AaronGilMartinez** [comment]
Fixed in #424
