### ISSUE TITLE
Theme branding

### ISSUE THREAD

**Issue by claudiu-cristea** [openeuropa/oe_bootstrap_theme#39]
Right now, the EU Agencies screenshot is shipped with the theme (https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/screenshot.png). We should change it to one reflecting the new theme name.

**Comment by papegaill** [comment]
Closing this issue as screenshots have been updated with following PR https://github.com/openeuropa/oe_bootstrap_theme/pull/10
