### ISSUE TITLE
Old CKE4 ckeditor_stylesheets doesn't apply on CKEditor 5

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_bootstrap_theme#404]
Change record https://www.drupal.org/node/3259165

Just wondering if this is going to be removed from oe_bootstrap_theme eventually or applied to CKEditor 5 (ckeditor5-stylesheets). Ideally all CSS should be scoped under .ck-content for CKEditor 5.
Thanks

**Comment by drishu** [comment]
we have a ckeditor 5 track that is in discovery, any issue should be reported after we upgrade to it
