### ISSUE TITLE
Drupal 10.3: 'responsive' is not a supported key.

### ISSUE THREAD

**Issue by piotrsmykaj** [openeuropa/oe_bootstrap_theme#411]
### The problem

Drupal 10.3 + oe_bootstrap_theme 

Error message:
`'responsive' is not a supported key.`

While saving an edit page of any text format using CKEditor 5, ex. http://web:8080/web/en/admin/config/content/formats/manage/full_html

This issue doesn't happen with Drupal 10.2 (downgrade fixes the issue).

Also, when removing below file, the problem is gone: https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/modules/oe_bootstrap_theme_helper/src/Plugin/Filter/BootstrapTable.php

**Comment by vengador** [comment]
Hello @piotrsmykaj,

In EMA corporate, we are in the middle of updating to 10.3 and we can confirm that we can replicate that issue.

**Comment by piotrsmykaj** [comment]
Hi @vengador, 
thanks for the confirmation.

**Comment by piotrsmykaj** [comment]
Dear @vengador,
Feel free to test a patch with the fix:
 
```
docker-compose exec web composer config --merge --json extra.patches.openeuropa/oe_bootstrap_theme '{"D10.3": "https://patch-diff.githubusercontent.com/raw/openeuropa/oe_bootstrap_theme/pull/412.patch"}'
docker-compose exec web composer i
docker-compose exec web drush cr
```

**Comment by vengador** [comment]
Hello @piotrsmykaj 

Your patch for ELA includes one modified in docker-compose.yml that is not related to this issue. I [rebuilt your patch locally](https://github.com/digit-devs/ema-ema-dev/pull/2010/commits/e5baa9bf7ebc5ebeb9f7826cbbe6a603c07511eb) removing that change and I applied it to EMA and it works!! I would recommend to rebuild that patch with things related to this issue and it would be perfect :)

Good job :1st_place_medal:

**Comment by piotrsmykaj** [comment]
Hi @vengador,

Thank you for checking it. I was receiving locally warnings related to the deprecated version parameter during work on this fix.
