### ISSUE TITLE
Extra space added to image/dateblock in card (search variant) in md size

### ISSUE THREAD

**Issue by msnassar** [openeuropa/oe_bootstrap_theme#414]
Because of https://github.com/openeuropa/oe_bootstrap_theme/pull/399/files, it is nice that now we have space between dateblock and content in card in mobile :)
I believe this change has been introduced to fix the issue on mobile. However, because of this change, other breakpoints are also affected... e.g. we noticed extra space added between the **image/dateblock** and content on md. See here https://digit-oesa.prd.fpfis.tech.ec.europa.eu/en/node/54

Current behavior:
![image](https://github.com/user-attachments/assets/3f20867d-006a-4f32-b8e4-7aed625a9acc)

**Proposed solution:**
- Add `mb-md-0` to `{% set _left_col_classes = 'col-md-3 col-lg-2 rounded mw-listing-img mb-3' %}
` https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/templates/patterns/card/pattern-card--variant-search.html.twig#L47

After adding `mb-md-0`:
![image](https://github.com/user-attachments/assets/a395e7f9-f439-4424-bc5d-e2598472f938)

**Comment by AaronGilMartinez** [comment]
Closed fixed by #426
