### ISSUE TITLE
bcl lib templates take precedence over override

### ISSUE THREAD

**Issue by drishu** [openeuropa/oe_bootstrap_theme#61]
For templates like input--submit and such, where they are declared both in the templates/bcl folder and in the override folder, the bcl one takes precendece as the folder gets parsed first by drupal.
This creates a problem as we would like to call the pattern and through the pattern finally the bcl template.

**One solution would be** to add `- "bcl"` under `file_scan_ignore_directories` in runner.dist.yml.

**Comment by drishu** [comment]
Today we discussed that the bcl folder should be added to the generated assets archive of a release, thus it should probably go into the assets folder.

**Comment by vever001** [comment]
Hello @drishu 

We are having some issues on UCPKN related to this: login form empty, discovered only on Drone (during behat) for some reason.
If I understand correctly:
- before: components were in templates/bcl
- and now: components are placed in in assets/bcl

BUT, even now, `drupal_find_theme_templates()` reads the tpls from assets/bcl.
For now, our only option is to add `bcl` to `file_scan_ignore_directories` but this is not the proper fix I think.
I believe components should have the `*.twig` extension, not `*.html.twig` which are meant as Drupal tpl overrides.

**Comment by claudiu-cristea** [comment]
@vever001 we've been discovered the same in Drone. Agree that `file_scan_ignore_directories` hack is not the correct way

**Comment by drishu** [comment]
Thank you @vever001 I will report this to the FRONT team.
cc @papegaill

**Comment by papegaill** [comment]
Sorry for the late reply, for me the templates can be placed anywhere, as long as the namespace is preserved. 
@brummbar any recommendation here based on oe_theme?

**Comment by brummbar** [comment]
I took a look too, and I wasn't aware that even having a custom loader like with ecl-twig-loader doesn't help in preventing the templates to be picked up by Drupal itself. In oe_theme we were lucky cause "ec/ecl-" prefix was present into the files, generating no collision...

**Comment by brummbar** [comment]
This has been fixed by renaming the components.
