### ISSUE TITLE
Is this supposed to be a base theme?

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/oe_bootstrap_theme#7]
We have been instructed to use this as the basis for the new Joinup theme. However it is not clear how this can be used, since this is not marked as a base theme in `oe_bootstrap_theme.info.yml`. Is this supposed to be a full theme that should not be extended by projects? Or is this simply a mistake and the intention is for this to be a base theme?

**Comment by claudiu-cristea** [comment]
Any full theme can be a base theme. Only the sub-theme should have a reference to the theme that it extends, by using the `base theme:` key.

**Comment by pfrenssen** [comment]
Ah yes you're right, I see this option now documented on https://www.drupal.org/docs/theming-drupal/defining-a-theme-with-an-infoyml-file#base-theme - I was not aware of this usage of setting it to `FALSE`. Thanks for the explanation!
