### ISSUE TITLE
Assets are missing from the release

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/oe_bootstrap_theme#9]
I see in `runner.yml.dist` that the `assets/` folder is supposed to be populated when a new release is made, but in the 1.0.0-alpha1 release this folder seems to be missing.

Can we update the tarballs or issue a new release which has this populated? The theme is not really usable without it.

**Comment by pfrenssen** [comment]
I have been experimenting with this in a fork: https://github.com/Joinup/oe_bootstrap_theme/releases/tag/1.0.0-alpha1

My findings so far:
1. AFAICS it is not possible to override the default source packages that are created by GitHub. The ones called `Source code (zip)` and `Source code (tar.gz)` are provided from the raw source and will not include any assets.
2. Apparently offering additional downloads is a paid service with a free tier. This is apparently limited to 1GB of download bandwidth per month (ref. https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository#about-git-lfs-objects-in-archives) - not sure that this free tier will be enough if multiple projects start pulling this in their CI pipelines on a regular basis.
3. We need documentation in the README explaining what users have to add to their `composer.json` and that they will need `openeuropa/composer-artifacts`.
4. Using `composer-artifacts` is not without problems, for example it does not support Composer 2, and the theme is downloaded in the wrong location - the `installer-paths` are ignored and the theme is placed in `vendor/` instead of in `web/themes/contrib/`.
5. Also when using `composer-artifacts` the dependencies of the theme (e.g. on the `ui-patterns` module) are ignored and need to be added manually to every project that uses the theme.
6. Things like checking out development branches / PRs or applying patches are not possible using `composer-artifacts`.

Is there already a suggested way of adding these artifacts to a release? I see a multitude of scripts, CLI tools and integrations on Github that offer this, but if a good one is already in use by the OE team this would save me a few hours of trying out ruby scripts :grin: It would be a good idea to clearly document the way to add the assets to a release in release procedure document.

**Comment by pfrenssen** [comment]
I've been considering this approach for the last two days but there are too many drawbacks associated with only being able to install the theme including assets from releases. Probably once the theme is stable and mature it will be fine to do this, but for the moment while it is in alpha and under heavy development we expect to be relying on patches.

We can unfortunately not compile the assets on the fly since our CI container has an old version of NPM which is not compatible. This is currently being worked on and hopefully this will be rectified in a few weeks. For the time being I'm going with a quick and dirty solution: I will create a fork of the theme in which the assets are committed to the repo. I don't plan on maintaining this for longer than necessary. Once we have a capable CI pipeline we will be able to compile the assets using NPM.

I will keep this ticket open since it is probably still a good idea to make release tarballs including the assets and document the way to do this in a release procedure.

**Comment by vever001** [comment]
Just passing by, on UCPKN and SRB, now that a compiled archive is included in each release we use openeuropa/composer artifacts to get it.
- composer require openeuropa/composer-artifacts:dev-master (only the master branch is composer 2 compatible ATM)
- Then paste the following in composer.json's extra section: 
```
"extra": {
        "artifacts": {
            "openeuropa/oe_bootstrap_theme": {
                "dist": {
                    "url": "https://github.com/{name}/releases/download/{pretty-version}/{project-name}-{pretty-version}.tar.gz",
                    "type": "tar"
                }
            }
        },
        ...
}
```

**Comment by brummbar** [comment]
This should be fixed now, we had issues in the past especially with composer artifacts and composer 2.x.
When we tag a release, drone will attach the compiled assets to a zip file that can be used with our composer-artifacts composer plugin.
Feel free to reopen if more information is needed.
